import { QUERY_KEYS } from "./queryKeys";
import { queryClient } from "./queryClient";
import {
  SUB_CATEGORY_TO_KR_MAP,
  SUB_CATEGORY_TO_ENG_MAP,
  CATEGORY_TO_SUB_CATEGORY_KR_ARRAY_MAP,
  CATEGORY_TO_SUB_CATEGORY_ENG_ARRAY_MAP
} from "./subCategoryMap";
import { JOB_DETAIL_FORM_MAP_TO_ENG, JOB_DETAIL_FORM_MAP_TO_KOR } from "./jobDetailFormMap";

export {
  QUERY_KEYS,
  queryClient,
  SUB_CATEGORY_TO_KR_MAP,
  SUB_CATEGORY_TO_ENG_MAP,
  CATEGORY_TO_SUB_CATEGORY_KR_ARRAY_MAP,
  CATEGORY_TO_SUB_CATEGORY_ENG_ARRAY_MAP,
  JOB_DETAIL_FORM_MAP_TO_ENG,
  JOB_DETAIL_FORM_MAP_TO_KOR
};